In [115]:
import pandas as pd
import numpy as np
from ast import literal_eval
df1 = pd.read_csv('August_Twitter.csv', encoding = 'utf8')
df1.head()

,Unnamed: 0,doc.coordinates,doc.created_at,doc.derived,doc.derived_from_id_str,doc.display_text_range,doc.entities,doc.extended_tweet,doc.favorite_count,doc.favorited,...,meta.rule_matcher,meta.telegram_channel,meta.tweet_type,meta.username,norm.author,norm.body,norm.domain,norm.id,norm.timestamp,norm.url
0,0,NaN,2022-09-12T00:00:01Z,NaN,NaN,"[0, 140]",{'urls': [{'display_url': 'pulsoguayaco.blogsp...,{'extended_entities': {'media': {'display_url'...,0,False,...,{'metadata': {'campaign_title': 'RPT - SLV 21-...,NaN,Original,NaN,pulsoguayaco,Qatar 2022: Diez atractivos tur√≠sticos de la s...,twitter.com,1569113567583907840,2022-09-12T00:00:01Z,https://twitter.com/pulsoguayaco/status/156911...
1,1,NaN,2022-09-12T00:00:09Z,NaN,NaN,NaN,{'urls': {'display_url': 'twitter.com/i/web/st...,NaN,0,False,...,"{'rule_id': '3665038', 'date_added': '2022-06-...",NaN,Retweet,IntelCrab,rogerm52,And there you have it. Confirmation of #Strile...,twitter.com,1569113598009409537,2022-09-12T00:00:09Z,https://twitter.com/rogerm52/status/1569113598...
2,2,NaN,2022-09-12T00:00:18Z,NaN,NaN,NaN,{'urls': {'display_url': 'twitter.com/i/web/st...,NaN,0,False,...,[{'metadata': {'campaign_title': 'Maduro Regim...,NaN,Retweet,VTVcanal8,franc73143668,#PREVENCI√ìNüò∑| Prevenir es tarea de todos. Sin ...,twitter.com,1569113638367293440,2022-09-12T00:00:18Z,https://twitter.com/franc73143668/status/15691...
3,3,NaN,2022-09-12T00:00:30Z,NaN,NaN,NaN,{'urls': {'display_url': 'twitter.com/i/web/st...,NaN,0,False,...,"[{'rule_id': '3313004', 'date_added': '2022-03...",NaN,Retweet,KyivIndependent,RickThurman7,‚ö°Ô∏èUS official: Ukraine should decide how to li...,twitter.com,1569113686018490368,2022-09-12T00:00:30Z,https://twitter.com/RickThurman7/status/156911...
4,4,NaN,2022-09-12T00:00:30Z,NaN,NaN,"[0, 140]",{'urls': {'display_url': 'twitter.com/i/web/st...,{'extended_entities': {'media': {'display_url'...,0,False,...,"{'rule_id': '3660723', 'date_added': '2022-06-...",NaN,Original,NaN,julian14117029,Kementerian PUPR gagas jalan Trans Papua Ruas ...,twitter.com,1569113686316285952,2022-09-12T00:00:30Z,https://twitter.com/julian14117029/status/1569...

In [4]:
df2=df1[['meta.author_id','meta.hashtag']].dropna()

In [4]:
h

0       ['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...
1                                ['Luhansk', 'Strilecha']
2                    ['LaCovid19NoEsGripe', 'PREVENCI√ìN']
4                 ['HasilOtsusBisaDirasakan', 'LawanOPM']
5           ['Panama', 'Chiriqui', 'Federalesdechiriqui']
                              ...
3986                            ['‰∏äÊµ∑', 'Áñ´ÊÉÖ', '‰∏≠Âúã', 'Ëø™Â£´Â∞º']
3990                                     PlanInvernal2022
3992                    ['LaCovid19NoEsGripe', 'EnVideo']
3993                          ['DisarmTPLF', 'SayNoMore']
3998                                           NotiMippCI
Name: meta.hashtag, Length: 1399, dtype: object

In [16]:
from ast import literal_eval

h = df2.dropna(subset = 'meta.hashtag')
h1 = h['meta.hashtag'].tolist()
h2 = []
for item in h1:

    try:
        h2.append(literal_eval(item))
    except:
        h2.append([item])
        continue

In [17]:
h['new_hashtag'] = h2
h.head()

,meta.author_id,meta.hashtag,new_hashtag
0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...","[ElSalvador, usa, M√©xico, Chile, Bolivia, Bras..."
1,856733766,"['Luhansk', 'Strilecha']","[Luhansk, Strilecha]"
2,1567055239555031042,"['LaCovid19NoEsGripe', 'PREVENCI√ìN']","[LaCovid19NoEsGripe, PREVENCI√ìN]"
4,1477248963392643073,"['HasilOtsusBisaDirasakan', 'LawanOPM']","[HasilOtsusBisaDirasakan, LawanOPM]"
5,1279492457982570497,"['Panama', 'Chiriqui', 'Federalesdechiriqui']","[Panama, Chiriqui, Federalesdechiriqui]"

print(len(h))
print(len(h2))

In [18]:
from ast import literal_eval
df2 = h
# df2['new_hashtag'] = [literal_eval(x) for x in df2['new_hashtag'].tolist()]
df2 = df2.explode('new_hashtag').reset_index()

In [19]:
df2.head()

,index,meta.author_id,meta.hashtag,new_hashtag
0,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",ElSalvador
1,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",usa
2,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",M√©xico
3,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",Chile
4,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",Bolivia

In [ ]:
# def extract(item):
#     try: 
#         return(item['name'])
#     except:
#         return(None)
# df2['meta.hashtag'] = [extract(x) for x in df2['meta.hashtag'].tolist()]

In [20]:
df2.head(len(df2['meta.author_id'].unique()))

,index,meta.author_id,meta.hashtag,new_hashtag
0,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",ElSalvador
1,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",usa
2,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",M√©xico
3,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",Chile
4,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",Bolivia
...,...,...,...,...
1203,1382,245163462,"['Ukraine', 'Putin', 'UkraineWar', 'Russia']",Russia
1204,1384,2775800485,"['Plenaria71', 'Independencia', 'ElSalvador']",Plenaria71
1205,1384,2775800485,"['Plenaria71', 'Independencia', 'ElSalvador']",Independencia
1206,1384,2775800485,"['Plenaria71', 'Independencia', 'ElSalvador']",ElSalvador
1207,1385,245956466,ÿßŸÑÿ≠ÿØÿ´,ÿßŸÑÿ≠ÿØÿ´

In [90]:
df2.rename(columns = {'meta.author_id' : 'MAID', 'meta.hashtag' : 'mh', 'new_hashtag' : 'newhash'}, inplace = True)

In [91]:
df2

,index,MAID,mh,newhash
0,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",ElSalvador
1,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",usa
2,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",M√©xico
3,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",Chile
4,0,984429894829592576,"['ElSalvador', 'usa', 'M√©xico', 'Chile', 'Boli...",Bolivia
...,...,...,...,...
3390,3992,1558207490956951563,"['LaCovid19NoEsGripe', 'EnVideo']",LaCovid19NoEsGripe
3391,3992,1558207490956951563,"['LaCovid19NoEsGripe', 'EnVideo']",EnVideo
3392,3993,2493875932,"['DisarmTPLF', 'SayNoMore']",DisarmTPLF
3393,3993,2493875932,"['DisarmTPLF', 'SayNoMore']",SayNoMore
3394,3998,1508961409912217607,NotiMippCI,NotiMippCI

In [108]:
len(df2.MAID.unique())

1208

In [ ]:
arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
          ['Captive', 'Wild', 'Captive', 'Wild']]
index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
df = pd.DataFrame({'Max Speed': [390., 350., 30., 20.]},
                 index=index)

In [123]:
len(df2.newhash.unique())

1685

In [131]:
df2.drop(columns=['mh'], inplace = True)

KeyError: "['mh'] not found in axis"

In [133]:
df2

      index                 MAID             newhash
0         0   984429894829592576          ElSalvador
1         0   984429894829592576                 usa
2         0   984429894829592576              M√©xico
3         0   984429894829592576               Chile
4         0   984429894829592576             Bolivia
...     ...                  ...                 ...
3390   3992  1558207490956951563  LaCovid19NoEsGripe
3391   3992  1558207490956951563             EnVideo
3392   3993           2493875932          DisarmTPLF
3393   3993           2493875932           SayNoMore
3394   3998  1508961409912217607          NotiMippCI

[3395 rows x 3 columns]

In [139]:
df3 = df2.groupby(['MAID'], as_index=False).agg({'newhash': '--'.join})

In [140]:
df3

                     MAID                                            newhash
0                15835430                        Assurance--QualityAssurance
1                16787760                                      El15Marchamos
2                17389650  ŒöœåœÉŒºŒøœÇ--ŒöŒ±ŒΩŒ±Œ¥Œ¨œÇ--œÉœÖŒΩŒ¨ŒΩœÑŒ∑œÉŒ∑--ŒöœåœÉŒºŒøœÇ--ŒöŒ±ŒΩŒ±Œ¥Œ¨œÇ--œÉ...
3                17485551                                         Nacionales
4                17653405  UkrainianCounteroffensive--Izyum--Donbas--Russ...
...                   ...                                                ...
1203  1567602516933709824                                             ÿßŸÑÿπÿ±ÿßŸÇ
1204  1567831983035764739                                 LaCovid19NoEsGripe
1205  1567967935196549120                                 LaCovid19NoEsGripe
1206  1568752322393812993                                     ‰π†ËøëÂπ≥--XiJinping
1207  1569091984496775170                                 LaCovid19NoEsGripe

[1208 rows x 2 columns]

In [188]:
df3[2,'newhash'].count()

TypeError: count() takes at least 1 argument (0 given)

In [158]:
df2.groupby(['newhash'])['MAID'].count().sort_values(ascending = False)

newhash
A3MesesDelSecuestroDelAvi√≥n    151
LaCovid19NoEsGripe             143
EnVideo                         93
SomosPatriaQueSeRespeta         67
RefuerzaTuVacuna                61
                              ...
Niedergang                       1
NewProfilePic                    1
NeverForget                      1
Netflix                          1
Ïù¥ÌéôÏä§                              1
Name: MAID, Length: 1685, dtype: int64

In [187]:
df2.groupby(['MAID'])['newhash'].count().sort_values(ascending = False)

MAID
1216550422191587328    37
1908437852             29
980407239943979008     29
1479937344610394117    29
970836236301631488     27
                       ..
1339666154441326592     1
1345205539987329024     1
1347319066164424706     1
1347748281544273920     1
1569091984496775170     1
Name: newhash, Length: 1208, dtype: int64